language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
node_js:
  - 13
  - 12
  - 10
  - 8
install:
  - yarn
  - yarn add codecov
jobs:
  include:
    - stage: test
    script: yarn prettier --check './{src,__mocks__}/**'
    script: yarn eslint './{src,__mocks__}/**'
    script: yarn jest --coverage
    script: yarn build
after_success:
  - yarn codecov

