language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 13
- 12
- 10
- 8
install:
- yarn
- yarn add codecov
script:
- yarn prettier --check './{src,__mocks__}/**'
- yarn eslint './{src,__mocks__}/**'
- yarn jest --coverage
- yarn build
after_success:
- yarn codecov
deploy:
  provider: npm
  email: riku.mantysalo@gmail.com
  api_key:
    secure: Y8KMF9aN95WaFD0zzf1TWw83jD57WdCguCZKv1FS0+a9SA/vsjUzF923hH88AsPrd5wWHGkQu7Gzih+5TAh+9grZqioEmxZavHgSapm8nDLBmMUsykyYAyTwCk4ymO3koLWsl7+J50HDZsxMdXGyaS76D1CRPz/XSDxG7pNqny9LjB/3DRgpOK1N9A/3SyD2KaQ/9Fe7IsuQ1fxwadRLj/fmi281j6bWHPVhVrUm0ydOHEpWx5MArUQavhLSu00W3+aYrHkYEuxYoJfw59DcyOVq4T7NOBA+Y4WVciYkXpUXLyuSDYY2xQH2jrZdrTcX+49OELRrzi9S/UD6zlXBwZo+1S99K1eIgwLGVc8wjQCS7UjUUGWuBwWPlnqGBhR71xYILiUXh8f/Od+VFWbXaIScknrbLuVqm4nRk6XjEU85fruMQi0BahSfsDx3vWmYMZxZLs1wFMfvrlXBl5ypTg6Ws1G1CTgL/fOrqv0i1JCBobMzUA0spF0CFpiS1cODYTYzgf/pmuduL2PuOkuvpWl/nD5N+LHt4RYYWvvxmfPtBSrcM8yVCCIhBqcwRjdmsPSEdb8/jxZV3kEV5z1RDeNUlc52pcnOlIN9Yx1vGjwhfC4wDrRfsn2XPIETTLb+0CxbT4YvLUAJgam8YiEtNrCuX+LM3XsTCdMDi41gfLk=
  on:
    tags: true
    repo: RikuMantysalo/ts-incremental-strict-mode
    branch: master
