language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
node_js:
  - 13
  - 12
  - 10
  - 9
  - 8
install:
  - yarn
script:
  - yarn prettier --check './{src,__mocks__}/**'
  - yarn eslint './{src,__mocks__}/**'
  - yarn test
  - yarn build

