name: Node CI
on: 
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 12, 13]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn
    - name: build and test other node versions
      if: matrix.node-version != 12
      run: |
        yarn jest
        yarn build
    - name: lint, test and build on node 12
      if: matrix.node-version == 12
      run: |
        yarn prettier --check './{src,__mocks__}/**'
        yarn eslint './{src,__mocks__}/**'
        yarn jest --coverage
        yarn build
        yarn add codecov
        yarn codecov
      env:
        CI: true
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
